name: Zeyad Abdelrahim
tagline: Machine Learning Researcher
career-objective: A highly motivated researcher with a demonstrated ability to translate complex machine learning concepts into practical solutions seeks a remote PhD program in Computer Vision, Machine Learning, or Robotics. Possesses strong research experience, having developed high-performance models using TensorFlow and Keras (e.g., 97% accuracy modulation recognition) and implemented RAG-based LLM solutions for clients. Proven ability to collaborate effectively with diverse teams and mentor students. Eager to leverage industry experience (e.g., R&D Data Scientist at Dell Technologies) with a strong academic foundation (M.Sc. in Communications Engineering) to contribute to the advancement of the field.
color-theme: red # red or blue
avatar-filename: my_pic.jpeg # Change to your avatar's filename
url: academicportfolio.github.io
baseurl: /
paginate: 5
paginate_path: "/blog/page:num/"

# Social Information
social:
  email: 
    visibility: true
    mail: zeyadabdelreheem@gmail.com
  github: 
    visibility: true
    handle: zeyad-abdelrahim
  linkedin: 
    visibility: true
    handle: zeyad-omar
  twitter: 
    visibility: false
    handle: zeyad

# Collections
collections:
  experience:
    output: true
    sort_by: order
  education:
    output: true
    sort_by: order
  projects:
    output: true
    sort_by: year
  skills:
    output: true
    sort_by: order
  publications:
    output: true
    sort_by: year
  volunteerexperience:
    output: false
    sort_by: order
  certifications:
    output: true
    sort_by: year
  achievements:
    output: true
    sort_by: order

# About Page Options
collection_option:
  experience: 
    label: Experience
    visibility: true
  education: 
    label: Education
    visibility: true
  projects: 
    label: Projects
    visibility: true
  skills: 
    label: Technical Skills
    visibility: true
  publications: 
    label: Publications
    visibility: true
  volunteerexperience: 
    label: Volunteer Experience
    visibility: false
  certifications: 
    label: Certifications
    visibility: true
  achievements: 
    label: Achievements
    visibility: true

navigation:
- title: About
  url: /
- title: Blog
  url: /blog/
- title: Contact
  url: /contact

include:
  - _pages

exclude:
  - readme.md

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      permalink: /:categories/:year/:month/:title
      layout: post
      comments: true
  - scope:
      path: ''
      type: projects
    values:
      permalink: /projects/:title
      layout: project
      comments: false
  - scope:
      path: ''
      type: publications
    values:
      permalink: /publications/:title
      layout: publication
      comments: false

# Disqus Comment
disqus:
  shortname: academic-portfolio # Change with your own disqus shortname

# Contact Form
formspree:
  endpoint: https://formspree.io/f/xdorkgkv # Change with your own form's endpoint

# Google Analytics
google_analytics: UAâ€”XXXXXXXX-X
